name: nihongo_lens

description: Subtitle scanner

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  image: ^4.2.0

flutter:
  uses-material-design: true
