name: nihongo_lens
description: Japanese to English live subtitle translator
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Speech recognition
  speech_to_text: ^6.6.0

  # Translation
  translator: ^1.0.0

  # Permissions
  permission_handler: ^11.3.1

  # Overlay window
  flutter_overlay_window: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
